### ISSUE TITLE
Wrong rotation

### ISSUE THREAD

**Issue by Ryan-Red** [Soldann/MORB_SLAM#26]
## Description of the Issue:
When driving normally and taking a normal turn, the SLAM keeps "turning" until it creates a new map.

## Possible solutions:
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/294 Mentions that this is due to ```Depth-Threshold = 0```. The solution is referenced in https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/107,  where you must do the following change:

``` if(mSensor==System::STEREO || mSensor==System::IMU_STEREO)``` to 
``` if(mSensor==System::STEREO || mSensor==System::IMU_STEREO || mSensor==System::RGBD)```

**Comment by ethanseq** [comment]
It seems that this issue was already taken care of in V1.0 (6 months ago). Here is a link to the new code https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/4452a3c4ab75b1cde34e5505a36ec3f9edcdc4c4/src/Tracking.cc#L1133
