### ISSUE TITLE
Fixing Stero_Inertial

### ISSUE THREAD

**Issue by Ryan-Red** [Soldann/MORB_SLAM#37]
## Description:
D435i crashes when running Stereo_Inertial.

## Fix:
Resolve by commenting out: ```'sensor.set_option(RS2_OPTION_AUTO_EXPOSURE_LIMIT,50000);```

See: https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/476

**Comment by DavidPetkovsek** [comment]
This was addressed in branch working-save-load-map and is now merged into master.
