### ISSUE TITLE
Save and Load maps

### ISSUE THREAD

**Issue by Ryan-Red** [Soldann/MORB_SLAM#5]
## Description
We want to be able to save and load maps using MORB-SLAM. Currently ``` Atlas.cc ``` is broken.

## Related Issues:
A few related issues such as [#535](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/535),  [#228](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/228), [#310](https://github.com/UZ-SLAMLab/ORB_SLAM3/pull/310) on ORB-SLAM3.

**Comment by Soldann** [comment]
Also [#581](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/581)

**Comment by Ryan-Red** [comment]
See https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/116, apparently system.cc has the map data and functions to output data

**Comment by Soldann** [comment]
Problems with existing orb_slam implementation https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/443
