### ISSUE TITLE
Stereo Segfault

### ISSUE THREAD

**Issue by ethanseq** [Soldann/MORB_SLAM#6]
Segfault occurs in Stereo after not receiving IMU data for a few successive frames.

**Comment by Soldann** [comment]
Relevant Issues: https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/540, https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/592, https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/476

**Comment by Soldann** [comment]
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/155
